### ISSUE TITLE
Handles when Transform Regex Does NOT match

### ISSUE THREAD

**Issue by liuderchi** [jljsj/style-utils#4]
In `getMatrix(t)` https://github.com/jljsj/style-utils/blob/master/index.jsx#L276

when `t` is not matched, `arr` should set to some default value like `[]`

e.g. when t is `"translateX(6px)"` it throws Error at `arr.length`

```js
export function getMatrix(t) {
  const arr = t.match(/(?:\-|\b)[\d\-\.e]+\b/gi);  // ⚠️ arr might be null
  const m = {};
  if (arr.length === 6) {
    m.m11 = parseFloat(arr[0]);
    // ... omit
  } else {
    // ... omit
  }
}
```

**Comment by jljsj33** [comment]
Where did you encounter such a problem? 
Need to work with `createMatrix`:
```js
getTransform(createMatrix('translateX(6px)').toString())
```

**Comment by liuderchi** [comment]
> Where did you encounter such a problem?

Happened when using jest snapshot testing, rendering with `mount()` from [`enzyme`](https://github.com/airbnb/enzyme)

<details><summary>Error Message with Calling Stack</summary>

<code>TypeError: Cannot read property 'length' of null</code>

      115 |
      116 |   it('should render ErrorMessages', () => {
    > 117 |     wrapper = mount(
          |               ^
      118 |       <ThemeProvider theme={theme}>
      119 |         <PurePrivilegeForm
      120 |           {...mockFormikAPIProps}

      at getMatrix (node_modules/style-utils/main.js:306:11)
      at getTransform (node_modules/style-utils/main.js:335:11)
      at node_modules/mcs-ui/node_modules/rc-tween-one/lib/plugin/StylePlugin.js:140:158
          at Array.forEach (<anonymous>)
      at StylePlugin.Object.<anonymous>.p.getAnimStart (node_modules/mcs-ui/node_modules/rc-tween-one/lib/plugin/StylePlugin.js:119:36)
      at node_modules/mcs-ui/node_modules/rc-tween-one/lib/Tween.js:210:32
          at Array.forEach (<anonymous>)
      at Tween.Object.<anonymous>.p.getAnimStartData (node_modules/mcs-ui/node_modules/rc-tween-one/lib/Tween.js:207:21)
      at node_modules/mcs-ui/node_modules/rc-tween-one/lib/Tween.js:304:34
          at Array.forEach (<anonymous>)
      at Tween.Object.<anonymous>.p.render (node_modules/mcs-ui/node_modules/rc-tween-one/lib/Tween.js:275:20)
      at Tween.Object.<anonymous>.p.frame (node_modules/mcs-ui/node_modules/rc-tween-one/lib/Tween.js:400:8)
      at TweenOne.frame (node_modules/mcs-ui/node_modules/rc-tween-one/lib/TweenOne.js:357:18)
      at TweenOne.raf (node_modules/mcs-ui/node_modules/rc-tween-one/lib/TweenOne.js:362:12)
      at TweenOne.start (node_modules/mcs-ui/node_modules/rc-tween-one/lib/TweenOne.js:293:14)
      at TweenOne.componentDidMount (node_modules/mcs-ui/node_modules/rc-tween-one/lib/TweenOne.js:80:14)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:14362:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:15463:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:138:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:15604:7)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:16619:34)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16564:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16483:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16455:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16355:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16219:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16786:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16813:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16840:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17123:3)
      at node_modules/react-dom/cjs/react-dom.development.js:17263:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16680:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17259:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17318:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:352:114)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:130:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
</details>

**Comment by jljsj33** [comment]
~Can you provide your jest code?~

jest getComputedStyle does not convert transform to matrix.

**Comment by jljsj33** [comment]
Don't set the transform in the style, there is no `DOMMatrix` in `jest`。
